import React, { useEffect, useRef } from 'react';
import { ThemeHeader } from '../../types/portfolio';
interface Props { text:string; header:ThemeHeader; pointer:{x:number;y:number;active:boolean}; }
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
export const Wrapped3DCanvas:React.FC<Props>=({text,header,pointer})=>{
 const ref=useRef<HTMLCanvasElement|null>(null); const pointerRef=useRef(pointer); pointerRef.current=pointer;
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;let raf=0;const start=performance.now();const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const render=(now:number)=>{const dpr=Math.min(window.devicePixelRatio||1,2),r=canvas.getBoundingClientRect(),w=Math.max(260,r.width),h=Math.max(90,r.height);const cw=Math.floor(w*dpr),ch=Math.floor(h*dpr);if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
 const p=pointerRef.current,mx=p.active?clamp(p.x,-1,1):0,my=p.active?clamp(p.y,-1,1):0,speed=clamp(header.animationSpeed??1,0,3),intensity=clamp(header.animationIntensity??1,0,2.5),perspective=clamp(header.animationPerspective??900,450,2200),depth=clamp(header.animationDepth??header.animationDepthPx??70,20,180),curve=clamp(header.wrappedCurve??1.15,.2,3),twist=clamp(header.wrappedTwist??1.25,0,3),bulge=clamp(header.wrappedBulge??1.1,.5,2.2),scale=clamp(header.wrappedScale??1,.65,1.35),glow=clamp(header.wrappedGlow??.35,0,1),t=reduced?0:(now-start)/1000*speed,surface=header.wrappedSurfaceColor||'#0A84FF',textColor=header.wrappedTextColor||'#FFFFFF';
 const cy=(u:number)=>h*.52+Math.sin((u-.5)*Math.PI*2.15*curve+t*.95)*h*.17*curve+Math.sin((u-.5)*Math.PI*5.2*curve-t*.7)*h*.055*curve+my*h*.08;
 const zAt=(u:number)=>Math.sin((u-.5)*Math.PI*2.4*twist+t*.75)*depth*.75+Math.sin((u-.5)*Math.PI*5.7*twist-t*.5)*depth*.2+mx*depth*.55*(u-.5)*intensity;
 const project=(x:number,y:number,z:number)=>{const q=perspective/(perspective-z);return{x:w/2+(x-w/2)*q*scale,y:h/2+(y-h/2)*q*scale,q}};
 const glowBg=ctx.createRadialGradient(w*.5,h*.5,0,w*.5,h*.5,w*.75);glowBg.addColorStop(0,surface+'22');glowBg.addColorStop(1,surface+'00');ctx.fillStyle=glowBg;ctx.fillRect(0,0,w,h);
 const n=96,top:{x:number;y:number}[]=[],bottom:{x:number;y:number}[]=[];
 for(let i=0;i<=n;i++){const u=i/n,z=zAt(u),half=h*(.34+.08*Math.cos((u-.5)*Math.PI*2.2*curve+t*.4))*bulge+Math.abs(z)*.045,c=cy(u);top.push(project(u*w,c-half,z));bottom.push(project(u*w,c+half,z))}
 ctx.save();ctx.beginPath();ctx.moveTo(top[0].x,top[0].y);for(let i=1;i<top.length;i++)ctx.lineTo(top[i].x,top[i].y);for(let i=bottom.length-1;i>=0;i--)ctx.lineTo(bottom[i].x,bottom[i].y);ctx.closePath();const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,surface);grad.addColorStop(.5,surface);grad.addColorStop(1,surface+'DD');ctx.fillStyle=grad;ctx.shadowColor=surface;ctx.shadowBlur=18*glow;ctx.fill();ctx.restore();
 ctx.save();ctx.globalAlpha=.3;ctx.beginPath();ctx.moveTo(top[0].x+8,top[0].y+9);for(let i=1;i<top.length;i++)ctx.lineTo(top[i].x+8,top[i].y+9);for(let i=bottom.length-1;i>=0;i--)ctx.lineTo(bottom[i].x+8,bottom[i].y+9);ctx.closePath();ctx.fillStyle='#001a33';ctx.fill();ctx.restore();
 const phrase=(text||'PORTFÓLIO').toUpperCase();const family=getComputedStyle(document.documentElement).getPropertyValue('--font-headings').trim()||'Arial, sans-serif';const fontSize=clamp(header.brandFontSizePx||28,20,64)*1.8;ctx.font=`${header.brandWeight||900} ${fontSize}px ${family}`;ctx.textBaseline='middle';ctx.textAlign='center';const widths=Array.from(phrase).map(ch=>ctx.measureText(ch).width),total=widths.reduce((a,b)=>a+b,0),fit=Math.min(1,w*.9/Math.max(total,1));let cursor=(w-total*fit)/2;
 Array.from(phrase).forEach((ch,i)=>{const gw=widths[i]*fit,x=cursor+gw/2,u=clamp(x/w,0,1),z=zAt(u),center=project(x,cy(u),z),du=.004,a=project(x-1,cy(clamp(u-du,0,1)),zAt(clamp(u-du,0,1))),b=project(x+1,cy(clamp(u+du,0,1)),zAt(clamp(u+du,0,1))),angle=Math.atan2(b.y-a.y,b.x-a.x)+mx*.1+Math.sin(t*.8+i*.25)*.02,s=clamp(center.q*fit,.72,1.22);
 ctx.save();ctx.translate(center.x+4,center.y+6);ctx.rotate(angle);ctx.scale(s,s);ctx.fillStyle='#001a33';ctx.globalAlpha=.5;ctx.fillText(ch,0,0);ctx.restore();ctx.save();ctx.translate(center.x,center.y);ctx.rotate(angle);ctx.scale(s,s);ctx.fillStyle=textColor;ctx.globalAlpha=1;ctx.shadowColor=surface;ctx.shadowBlur=glow*7;ctx.fillText(ch,0,0);ctx.restore();cursor+=gw});
 if(p.active){const gx=w/2+mx*w*.22,gy=h/2+my*h*.18,rg=ctx.createRadialGradient(gx,gy,0,gx,gy,h*.3);rg.addColorStop(0,'#ffffff22');rg.addColorStop(1,'#ffffff00');ctx.fillStyle=rg;ctx.fillRect(0,0,w,h)}
 raf=requestAnimationFrame(render)};raf=requestAnimationFrame(render);return()=>cancelAnimationFrame(raf)},[text,header]);
 return <canvas ref={ref} className="wrapped-3d-canvas" aria-label={text} role="img"/>;
};
